[package]
name = "turbe"
version = "0.1.0"
edition = "2024"

[package.metadata.turbo]
user = "8157b78b-7c27-48b0-8a01-5efd426cd87d"

[dependencies]
turbo = { version = "5.0.0", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
